QuanLyKho/Models/NHACUNGCAP.cs
namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Xml.Linq;

    [Table("NHACUNGCAP")]
    public partial class NHACUNGCAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHACUNGCAP()
        {
            SANPHAMs = new HashSet<SANPHAM>();
        }

        [Key]
        [Display(Name="Mã nhà cung cấp ")]
        public int MaNCC { get; set; }

        [Required(ErrorMessage = "Tên nhà cung cấp không được để trống")]
        [Display(Name = "Tên nhà cung cấp")]
        [StringLength(255)]
        public string TenNCC { get; set; }

        [Required(ErrorMessage = "Địa chỉ nhà cung cấp không được để trống")]
        [Display(Name = "Địa chỉ nhà cung cấp")]
        [StringLength(255)]
        public string DiachiNCC { get; set; }

        [Required(ErrorMessage = "Mời nhập số điện thoại nhà cung cấp")]
        [Display(Name = "Số điện thoại nhà cung cấp")]
        [StringLength(20)]
        public string SDTNCC { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}

QuanLyKho/Controllers/NHACUNGCAPsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyKho.Models;

namespace QuanLyKho.Controllers
{
    public class NHACUNGCAPsController : Controller
    {
        private QLKhoDBContext db = new QLKhoDBContext();

        // GET: NHACUNGCAPs
        public ActionResult Index(String thanhPho)
        {
            if (Session["Taikhoan"] != null)
            {
                var nhaCungCap = db.NHACUNGCAPs.AsQueryable();

                if (!string.IsNullOrEmpty(thanhPho))
                {
                    var diaChiFilter = thanhPho.Trim().ToLower();
                    var diaChiFilterEnd = diaChiFilter.Split(',').LastOrDefault()?.Trim();
                    if (!string.IsNullOrEmpty(diaChiFilterEnd))
                    {
                        nhaCungCap = nhaCungCap.Where(ncc => ncc.DiachiNCC.ToLower().EndsWith(diaChiFilterEnd));
                    }
                }

                return View(nhaCungCap.ToList());
            }
            else
                return RedirectToAction("Dangnhap", "Login");
        }

        // GET: NHACUNGCAPs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHACUNGCAP nHACUNGCAP = db.NHACUNGCAPs.Find(id);
            if (nHACUNGCAP == null)
            {
                return HttpNotFound();
            }
            return View(nHACUNGCAP);
        }

        // GET: NHACUNGCAPs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NHACUNGCAPs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNCC,TenNCC,DiachiNCC,SDTNCC")] NHACUNGCAP nHACUNGCAP)
        {
            if (ModelState.IsValid)
            {
                db.NHACUNGCAPs.Add(nHACUNGCAP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nHACUNGCAP);
        }

        // GET: NHACUNGCAPs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHACUNGCAP nHACUNGCAP = db.NHACUNGCAPs.Find(id);
            if (nHACUNGCAP == null)
            {
                return HttpNotFound();
            }
            return View(nHACUNGCAP);
        }

        // POST: NHACUNGCAPs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNCC,TenNCC,DiachiNCC,SDTNCC")] NHACUNGCAP nHACUNGCAP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nHACUNGCAP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nHACUNGCAP);
        }

        // GET: NHACUNGCAPs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHACUNGCAP nHACUNGCAP = db.NHACUNGCAPs.Find(id);
            if (nHACUNGCAP == null)
            {
                return HttpNotFound();
            }
            return View(nHACUNGCAP);
        }

        // POST: NHACUNGCAPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NHACUNGCAP nHACUNGCAP = db.NHACUNGCAPs.Find(id);
            db.NHACUNGCAPs.Remove(nHACUNGCAP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteSelected(string[] selectedIds)
        {
            if (selectedIds != null && selectedIds.Length > 0)
            {
                foreach (var id in selectedIds)
                {
                    if (int.TryParse(id, out int Id))
                    {
                        var xoa = db.NHACUNGCAPs.Find(Id);
                        if (xoa != null)
                        {
                            db.NHACUNGCAPs.Remove(xoa);
                        }
                    }
                }
                db.SaveChanges();
            }
            return new EmptyResult();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyKho/Views/NHACUNGCAPs/Create.cshtml
@model QuanLyKho.Models.NHACUNGCAP

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    <h4>NHACUNGCAP</h4>
    <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNCC, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập tên nhà cung cấp" } })
                @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiachiNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiachiNCC, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập địa chỉ nhà cung cấp" } })
                @Html.ValidationMessageFor(model => model.DiachiNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDTNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDTNCC, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập số điện thoại nhà cung cấp"} })
                @Html.ValidationMessageFor(model => model.SDTNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-outline-success" style="margin-right:5px" />
                <a href="@Url.Action("Index","KHOHANGs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
            </div>
        </div>
    </div>
}

QuanLyKho/Views/NHACUNGCAPs/Delete.cshtml
@model QuanLyKho.Models.NHACUNGCAP

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NHACUNGCAP</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiachiNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiachiNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDTNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDTNCC)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-outline-danger" style="margin-right:8px" />
            <a href="@Url.Action("Index","NHACUNGCAPs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
        </div>
    }
</div>

QuanLyKho/Views/NHACUNGCAPs/Details.cshtml
@model QuanLyKho.Models.NHACUNGCAP

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Details</h2>

<div>
    <h4>NHACUNGCAP</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiachiNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiachiNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDTNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDTNCC)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit","NHACUNGCAPs",new { id = Model.MaNCC})" class="btn btn-outline-success" >Sửa</a>
    <a href="@Url.Action("Index","NHACUNGCAPs")" class="btn btn-outline-success" >Trở về <i class="fas fa-arrow-circle-left"></i></a>
</p>

QuanLyKho/Views/NHACUNGCAPs/Edit.cshtml
@model QuanLyKho.Models.NHACUNGCAP

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NHACUNGCAP</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNCC)

        <div class="form-group">
            @Html.LabelFor(model => model.TenNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiachiNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiachiNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiachiNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDTNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDTNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDTNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-outline-success" style="margin-right:5px" />
                <a href="@Url.Action("Index","NHACUNGCAPs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
            </div>
        </div>
    </div>
}

QuanLyKho/Views/NHACUNGCAPs/Index.cshtml
@model IEnumerable<QuanLyKho.Models.NHACUNGCAP>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Index nha cung cap</h2>

<a href="@Url.Action("Create", "NHACUNGCAPs")" class="btn btn-outline-success">Thêm</a>
<button id="deleteSelectedNCC" class="btn btn-outline-danger" style="position:fixed; margin-left:3px"><i class="fas fa-trash-alt"></i></button>
<div class=" card-body">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th><input type="checkbox" id="checkAll" /></th>
                <th>Nhà cung cấp</th>
                <th>
                    <form method="get">
                        <div class="form-group">
                            <label>Địa chỉ:</label>
                            <select name="thanhPho" class="form-control" onchange="this.form.submit()" style="width:129px">
                                <option value="">--Tỉnh--</option>
                                <option value="TP.HCM">TP.HCM</option>
                                <option value="TP.Hà Nội">TP.Hà Nội</option>
                            </select>
                        </div>
                    </form>
                </th>
                <th>Số điện thoại</th>
                <th>Chức năng</th>
            </tr>
        </thead>

        <tbody class="search" style="font-size:13px">
            @foreach (var item in Model)
            {

                <tr>
                    <td class="text-center"><input type="checkbox" class="checkbox" value="@item.MaNCC" /></td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenNCC)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DiachiNCC)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SDTNCC)
                    </td>
                    <td style="display:flex; border-bottom:0px">
                        <a href="@Url.Action("Edit","NHACUNGCAPs",new { id = item.MaNCC})" class="btn btn-outline-dark">Sửa</a>
                        <a href="@Url.Action("Details","NHACUNGCAPs",new { id = item.MaNCC })" class="btn btn-outline-info">Chi tiết</a>
                        <a href="@Url.Action("Delete","NHACUNGCAPs",new { id =item.MaNCC})" class="btn btn-outline-danger">Xóa</a>
                    </td>
                </tr>

            }
         </tbody>
    </table>
</div>