QuanLyKho/Models/SANPHAM.cs
namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SANPHAM")]
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            CTPHIEUNHAPKHOes = new HashSet<CTPHIEUNHAPKHO>();
            CTPHIEUXUATKHOes = new HashSet<CTPHIEUXUATKHO>();
            VITRISPs = new HashSet<VITRISP>();
        }
        [Key]
        [Display(Name = "Mã sản phẩm")]
        public int MaSP { get; set; }


        [StringLength(255)]
        [Required(ErrorMessage = "Mời nhập tên sản phẩm")]
        [Display(Name = "Tên sản phẩm")]

        public string TenSP { get; set; }

        [Required(ErrorMessage = "Mời nhập mô tả")]
        [Display(Name = "Mô tả")]
        public string Mota { get; set; }

        [Required(ErrorMessage = "Mời nhập đơn giá")]
        [Display(Name = "Đơn giá ")]
        public double DonGia { get; set; }

        
        [StringLength(50)]
        [Required(ErrorMessage = "Mời nhập đơn vị tính (Kg,Cái,..) ")]
        [Display(Name = "Đơn vị tính")]
        public string DonViTinh { get; set; }

        [Required(ErrorMessage = "Mời nhập số lượng tồn > 0 ")]
        [Display(Name = "Số lượng tồn")]
        public int SoLuongTon { get; set; }

        [StringLength(255)]
        public string HinhAnh { get; set; }


        [Required(ErrorMessage = "Khối lượng không được để trống")]
        [Range(1, double.MaxValue, ErrorMessage = "Khối lượng phải phải lớn hơn 0")]
        public double? KhoiLuong { get; set; }


        [Display(Name = "Mã nhà cung cấp")]
        public int MaNCC { get; set; }

        [Display(Name = "Mã nhóm sản phẩm")]
        public int MaNhomSP { get; set; }

        //[Key]
        //[Display(Name = "Mã sản phẩm")]
        //public int MaSP { get; set; }

        //[Required(ErrorMessage = "Mời nhập tên sản phẩm")]
        //[Display(Name = "Tên sản phẩm")]
        //[StringLength(255)]
        //public string TenSP { get; set; }
        //[Required(ErrorMessage = "Mời nhập mô tả")]
        //[Display(Name = "Mô tả")]

        //[StringLength(255)]
        //public string Mota { get; set; }

        //[Required(ErrorMessage = "Mời nhập đơn giá")]
        //[Display(Name = "Đơn giá ")]
        //public double DonGia { get; set; }

        //[Required(ErrorMessage = "Mời nhập đơn vị tính (Kg,Cái,..) ")]
        //[Display(Name = "Đơn vị tính")]
        //[StringLength(50)]
        //public string DonViTinh { get; set; }
        //[Required(ErrorMessage = "Mời nhập số lượng tồn > 0 ")]
        //[Display(Name = "Số lượng tồn")]

        //public int SoLuongTon { get; set; }
        //[Display(Name = "Hình ảnh")]

        //[StringLength(255)]
        //public string HinhAnh { get; set; }

        //[Required(ErrorMessage ="Khối lượng không được để trống")]
        //[Range(1, double.MaxValue, ErrorMessage = "Khối lượng phải phải lớn hơn 0")]
        //public double KhoiLuong { get; set; }

        //[Display(Name = "Mã nhà cung cấp")]
        //public int MaNCC { get; set; }

        //[Display(Name = "Mã nhóm sản phẩm")]
        //public int MaNhomSP { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAPKHO> CTPHIEUNHAPKHOes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUXUATKHO> CTPHIEUXUATKHOes { get; set; }

        public virtual NHACUNGCAP NHACUNGCAP { get; set; }

        public virtual NHOMSANPHAM NHOMSANPHAM { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VITRISP> VITRISPs { get; set; }
    }
}

QuanLyKho/Controllers/SANPHAMsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using PagedList;
using QuanLyKho.Models;

namespace QuanLyKho.Controllers
{
    public class SANPHAMsController : Controller
    {
        private QLKhoDBContext db = new QLKhoDBContext();

        // GET: SANPHAMs
        public ActionResult Index(String sortOrder, String nhomSP, int? page, string searchString)
        {
            if (Session["Taikhoan"] != null)
            {
                ViewBag.SortOrder = sortOrder;
                var sanPham = db.SANPHAMs.AsQueryable();

                if (!string.IsNullOrEmpty(nhomSP))
                {
                    sanPham = sanPham.Where(sp => sp.NHOMSANPHAM.TenNhomSP == nhomSP);
                }
                switch (sortOrder)
                {
                    case "asc":
                        sanPham = sanPham.OrderBy(sp => sp.SoLuongTon);
                        break;
                    case "desc":
                        sanPham = sanPham.OrderByDescending(sp => sp.SoLuongTon);
                        break;
                    case "asc-price":
                        sanPham = sanPham.OrderBy(sp => sp.DonGia);
                        break;
                    case "desc-price":
                        sanPham = sanPham.OrderByDescending(sp => sp.DonGia);
                        break;
                    default:
                        sanPham = sanPham.OrderBy(sp => sp.TenSP);
                        break;
                }
                return View(sanPham.ToList());
            }
            else
                return RedirectToAction("Dangnhap", "Login");
        }

        // GET: SANPHAMs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.SANPHAMs.Find(id);
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            return View(sANPHAM);
        }

        // GET: SANPHAMs/Create
        public ActionResult Create()
        {
            ViewBag.MaNCC = new SelectList(db.NHACUNGCAPs, "MaNCC", "TenNCC");
            ViewBag.MaNhomSP = new SelectList(db.NHOMSANPHAMs, "MaNhomSP", "TenNhomSP");
            return View();
        }

        // POST: SANPHAMs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,Mota,DonGia,DonViTinh,SoLuongTon,NgayNhap,HinhAnh,KhoiLuong,MaNCC,MaNhomSP")] SANPHAM sANPHAM, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    sANPHAM.HinhAnh = fileName;
                }

                db.SANPHAMs.Add(sANPHAM);
                db.SaveChanges();

                if (file != null && file.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/images"), sANPHAM.HinhAnh);
                    file.SaveAs(path);
                }

                return RedirectToAction("Index");
            }

            ViewBag.MaNCC = new SelectList(db.NHACUNGCAPs, "MaNCC", "TenNCC", sANPHAM.MaNCC);
            ViewBag.MaNhomSP = new SelectList(db.NHOMSANPHAMs, "MaNhomSP", "TenNhomSP", sANPHAM.MaNhomSP);
            return View(sANPHAM);
        }

        // GET: SANPHAMs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.SANPHAMs.Find(id);
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNCC = new SelectList(db.NHACUNGCAPs, "MaNCC", "TenNCC", sANPHAM.MaNCC);
            ViewBag.MaNhomSP = new SelectList(db.NHOMSANPHAMs, "MaNhomSP", "TenNhomSP", sANPHAM.MaNhomSP);
            return View(sANPHAM);
        }

        // POST: SANPHAMs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,Mota,DonGia,DonViTinh,SoLuongTon,NgayNhap,HinhAnh,KhoiLuong,MaNCC,MaNhomSP")] SANPHAM sANPHAM, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    sANPHAM.HinhAnh= fileName;

                    var path = Path.Combine(Server.MapPath("~/images/"), fileName);
                    file.SaveAs(path);
                }
                else
                {
                    var sanphamcu = db.SANPHAMs.Find(sANPHAM.MaSP);
                    sANPHAM.HinhAnh = sanphamcu.HinhAnh;
                }
                db.SANPHAMs.AddOrUpdate(sANPHAM);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNCC = new SelectList(db.NHACUNGCAPs, "MaNCC", "TenNCC", sANPHAM.MaNCC);
            ViewBag.MaNhomSP = new SelectList(db.NHOMSANPHAMs, "MaNhomSP", "TenNhomSP", sANPHAM.MaNhomSP);
            return View(sANPHAM);
        }

        // GET: SANPHAMs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.SANPHAMs.Find(id);
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            return View(sANPHAM);
        }

        // POST: SANPHAMs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SANPHAM sANPHAM = db.SANPHAMs.Find(id);
            db.SANPHAMs.Remove(sANPHAM);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult DeleteSelected(string[] selectedIds)
        {
            if (selectedIds != null && selectedIds.Length > 0)
            {
                foreach (var id in selectedIds)
                {
                    if (int.TryParse(id, out int sanPhamId))
                    {
                        var sanPham = db.SANPHAMs.Find(sanPhamId);
                        if (sanPham != null)
                        {
                            db.SANPHAMs.Remove(sanPham);
                        }
                    }
                }
                db.SaveChanges();
            }

            return new EmptyResult();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyKho/Views/SANPHAMs/Create.cshtml
@model QuanLyKho.Models.SANPHAM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "SANPHAMs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SANPHAM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập tên sản phẩm" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập mô tả" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập đơn giá" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonViTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập đơn vị tính (Kg,Cái,...)" } })
                @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập số lượng tồn" } })
                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2" for="HinhAnh">Hình ảnh</label>
            <div class="col-md-10">
                <input type="file" name="file" id="HinhAnh" />
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.KhoiLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KhoiLuong, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập khối lượng lớn hơn 0" } })
                @Html.ValidationMessageFor(model => model.KhoiLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, "MaNCC", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNhomSP, "MaNhomSP", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNhomSP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNhomSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-outline-success" style="margin-right:5px" />
                <a href="@Url.Action("Index","SANPHAMs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
            </div>
        </div>
    </div>
}

QuanLyKho/Views/SANPHAMs/Delete.cshtml
@model QuanLyKho.Models.SANPHAM

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SANPHAM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NHACUNGCAP.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHACUNGCAP.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NHOMSANPHAM.TenNhomSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHOMSANPHAM.TenNhomSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonViTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonViTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            <img src="@Url.Content("~/images/" + Model.HinhAnh)" width="100" />
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-outline-danger" style="margin-right:8px" />
            <a href="@Url.Action("Index","SANPHAMs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
        </div>
    }

</div>

QuanLyKho/Views/SANPHAMs/Details.cshtml
@model QuanLyKho.Models.SANPHAM

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SANPHAM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NHACUNGCAP.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHACUNGCAP.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NHOMSANPHAM.TenNhomSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHOMSANPHAM.TenNhomSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonViTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonViTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit","SANPHAMs",new { id = Model.MaSP})" class="btn btn-outline-success">Sửa</a>
    <a href="@Url.Action("Index","SANPHAMs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
</p>

QuanLyKho/Views/SANPHAMs/Edit.cshtml
@model QuanLyKho.Models.SANPHAM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "SANPHAMs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>SANPHAM</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaSP)

    <div class="form-group">
        @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DonViTinh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <label class="control-label col-md-2" for="HinhAnh">Hình ảnh</label>
        <div class="col-md-10">
            @if (!string.IsNullOrEmpty(Model.HinhAnh))
            {
                <img src="@Url.Content("~/images/" + Model.HinhAnh)" width="100px" />
            }
            <input type="file" name="file" id="HinhAnh" />
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KhoiLuong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KhoiLuong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KhoiLuong, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.MaNCC, "MaNCC", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaNhomSP, "MaNhomSP", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaNhomSP", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaNhomSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Sửa" class="btn btn-outline-success" style="margin-right:5px" />
            <a href="@Url.Action("Index","NHANVIENs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
        </div>
    </div>
</div>
}