QuanLyKho/Models/NHANVIEN.cs
namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("NHANVIEN")]
    public partial class NHANVIEN
    {
        [Key]
        [Display(Name = "Mã nhân viên")]
        public int MaNV { get; set; }

        [Required(ErrorMessage = "Mời nhập tên nhân viên")]
        [Display(Name = "Tên nhân viên")]
        [StringLength(255)]
        public string TenNV { get; set; }

        [Required(ErrorMessage = "Email không được bỏ trống")]
        [EmailAddress(ErrorMessage = "Địa chỉ email không hợp lệ")]
        [Display(Name = "Nhập Email")]
        [StringLength(255)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        [RegularExpression(@"(?=.*[a-zA-Z])(?=.*\d)[@a-zA-Z\d]{8,}$", ErrorMessage = "Mật khẩu phải có độ dài tối thiểu là 8 ký tự và chứa ít nhất một ký tự đặc biệt @")]
        [Display(Name = "Mật khẩu")]
        [StringLength(50)]
        public string MatKhau { get; set; }


        [Display(Name = "Hình ảnh")]
        [Column(TypeName = "text")]
        public string ImgUrl { get; set; }

        [Display(Name = "Mã chức vụ")]
        public int MaCV { get; set; }

        public virtual CHUCVU CHUCVU { get; set; }
    }

}

QuanLyKho/Controllers/NHANVIENsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using QuanLyKho.Models;



namespace QuanLyKho.Controllers
{
    public class NHANVIENsController : Controller
    {
        private QLKhoDBContext db = new QLKhoDBContext();

        // GET: NHANVIENs
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }
        public ActionResult Index(String chucVu, int? page)
        {
            if (Session["Taikhoan"] != null )
            {
                var nhanVien = db.NHANVIENs.AsQueryable();
                if (!string.IsNullOrEmpty(chucVu))
                {
                    nhanVien = nhanVien.Where(nv => nv.CHUCVU.TenCV == chucVu);
                }
                nhanVien = nhanVien.OrderBy(nv => nv.MaNV);
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                return View(nhanVien.ToPagedList(pageNumber, pageSize));
                
            }else 
                return RedirectToAction("Dangnhap", "Login"); 
            
            
        }

        // GET: NHANVIENs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            return View(nHANVIEN);
        }

        // GET: NHANVIENs/Create
        public ActionResult Create()
        {
            ViewBag.MaCV = new SelectList(db.CHUCVUs, "MaCV", "TenCV");
            return View();
        }

        // POST: NHANVIENs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,TenNV,Email,MatKhau,ImgUrl,MaCV")] NHANVIEN nHANVIEN, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    nHANVIEN.ImgUrl = fileName;
                }
                nHANVIEN.MatKhau = GetMD5(nHANVIEN.MatKhau);
                db.NHANVIENs.Add(nHANVIEN);
                db.SaveChanges();

                if (file != null && file.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/images"), nHANVIEN.ImgUrl);
                    file.SaveAs(path);
                }

                return RedirectToAction("Index");
            }

            ViewBag.MaCV = new SelectList(db.CHUCVUs, "MaCV", "TenCV", nHANVIEN.MaCV);
            return View(nHANVIEN);
        }

        // GET: NHANVIENs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaCV = new SelectList(db.CHUCVUs, "MaCV", "TenCV", nHANVIEN.MaCV);
            return View(nHANVIEN);
        }

        // POST: NHANVIENs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,TenNV,Email,MatKhau,ImgUrl,MaCV")] NHANVIEN nHANVIEN, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    nHANVIEN.ImgUrl = fileName;

                    var path = Path.Combine(Server.MapPath("~/images/"), fileName);
                    file.SaveAs(path);
                }
                else
                {
                    var nhanVienCu = db.NHANVIENs.Find(nHANVIEN.MaNV);
                    nHANVIEN.ImgUrl = nhanVienCu.ImgUrl;
                }
                nHANVIEN.MatKhau = GetMD5(nHANVIEN.MatKhau);
                db.NHANVIENs.AddOrUpdate(nHANVIEN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaCV = new SelectList(db.CHUCVUs, "MaCV", "TenCV", nHANVIEN.MaCV);
            return View(nHANVIEN);
        }

        // GET: NHANVIENs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            return View(nHANVIEN);
        }

        // POST: NHANVIENs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            db.NHANVIENs.Remove(nHANVIEN);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteSelected(string[] selectedIds)
        {
            if (selectedIds != null && selectedIds.Length > 0)
            {
                foreach (var id in selectedIds)
                {
                    if (int.TryParse(id, out int nhanVienId))
                    {
                        var nhanVien = db.NHANVIENs.Find(nhanVienId);
                        if (nhanVien != null)
                        {
                            db.NHANVIENs.Remove(nhanVien);
                        }
                    }
                }
                db.SaveChanges();
            }

            return new EmptyResult();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyKho/Views/NHANVIENs/Create.cshtml
@model QuanLyKho.Models.NHANVIEN

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "NHANVIENs", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>NHANVIEN</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2" for="TenNV">Họ và Tên:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập tên nhân viên" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Email">Gmail:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MatKhau">Mật Khẩu:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập mật khẩu trên 8 ký tự" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ImgUrl">Hình ảnh:</label>
            <div class="col-md-10">
                <input type="file" name="file" id="ImgUrl" class="form-control" />
                @Html.ValidationMessageFor(model => model.ImgUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MaCV">Chức vụ:</label>
            <div class="col-md-10">
                @Html.DropDownList("MaCV", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaCV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-outline-success" style="margin-right:5px" />
                <a href="@Url.Action("Index","NHANVIENs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
            </div>
        </div>
    </div>
}

QuanLyKho/Views/NHANVIENs/Delete.cshtml
@model QuanLyKho.Models.NHANVIEN

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NHANVIEN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt> Chức vụ:</dt>

        <dd>
            @Html.DisplayFor(model => model.CHUCVU.TenCV)
        </dd>

        <dt>Họ và Tên </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>Gmail</dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>Mật khẩu</dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>Hình ảnh</dt>

        <dd>
            @Html.DisplayFor(model => model.ImgUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-outline-danger" style="margin-right:8px; padding:8px"/> 
            <a href="@Url.Action("Index","NHANVIENs")" class="btn btn-outline-success" style="padding: 8px">Trở về <i class="fas fa-arrow-circle-left"></i></a>
        </div>
    }
</div>

QuanLyKho/Views/NHANVIENs/Details.cshtml
@model QuanLyKho.Models.NHANVIEN

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Details</h2>

<div>
    <h4>NHANVIEN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt> Chức vụ:</dt>

        <dd>
            @Html.DisplayFor(model => model.CHUCVU.TenCV)
        </dd>

        <dt>Họ và Tên </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>Gmail:<dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>Mật khẩu:</dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>Hình ảnh:</dt>

        <dd>
            @Html.DisplayFor(model => model.ImgUrl)
        </dd>
    </dl>
</div>
<p>
    <a href="@Url.Action("Edit","NHANVIENs",new { id = Model.MaNV})" class="btn btn-outline-success" style="padding:8px">Sửa</a>
    <a href="@Url.Action("Index","NHANVIENs")" class="btn btn-outline-success" style="padding: 8px">Trở về <i class="fas fa-arrow-circle-left"></i></a>
</p>

QuanLyKho/Views/NHANVIENs/Edit.cshtml
@model QuanLyKho.Models.NHANVIEN

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "NHANVIENs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NHANVIEN</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

        <div class="form-group">
            <label class="control-label col-md-2" for="TenNV">Họ và Tên:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Email">Gmail:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MatKhau">Mật Khẩu:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ImgUrl">Hình ảnh:</label>
            <div class="col-md-10">
                <img src="~/images/@Model.ImgUrl" style="width:100px"/>
                <input type="file" name="file" id="ImgUrl" class="form-control" />
                @Html.ValidationMessageFor(model => model.ImgUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MaCV">Chức vụ:</label>
            <div class="col-md-10">
                @Html.DropDownList("MaCV", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaCV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group ">
            <div class="col-md-offset-2 col-md-10 d-xl-inline-flex">
                <input type="submit" value="Lưu" class="btn btn-outline-success" style="margin-right:5px" />
                <a href="@Url.Action("Index","NHANVIENs")" class="btn btn-outline-success" style="padding: 8px">Trở về <i class="fas fa-arrow-circle-left"></i></a>
            </div>
        </div>
    </div>
}

QuanLyKho/Views/NHANVIENs/Index.cshtml
@using PagedList.Mvc
@using QuanLyKho.Models
@model PagedList.PagedList<QuanLyKho.Models.NHANVIEN>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Index NhanVien</h2>


<a href="@Url.Action("Create","NHANVIENs")" class="btn btn-outline-success "><i class="fas fa-user-plus"></i></a>
<button id="deleteSelectedNV" class="btn btn-outline-danger"><i class="fas fa-trash-alt"></i></button>
<div class="card-body">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th><input type="checkbox" id="checkAll" /></th>
                <th>
                    <form method="get">
                        <div class="form-group">
                            <label>Chức vụ:</label>
                            <select name="chucVu" class="form-control" onchange="this.form.submit()" style="width:129px">
                                <option value="">--Chức vụ--</option>
                                <option value="Quản Lý">Quản lý</option>
                                <option value="Giam Doc">Giám đốc</option>
                                <option value="Thủ Kho">Thủ kho</option>
                            </select>
                        </div>
                    </form>
                </th>
                <th>Tên nhân viên</th>
                <th>Email</th>
                <th>Mật khẩu</th>
                <th>Ảnh</th>
                <th>Chức năng</th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center"><input type="checkbox" class="checkbox" value="@item.MaNV" /></td>
                <td>
                    @Html.DisplayFor(modelItem => item.CHUCVU.TenCV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MatKhau)
                </td>
                <td>
                    <img src="~/images/@item.ImgUrl" style="width:50px" />
                </td>
                <td>
                    <a href="@Url.Action("Edit","NHANVIENs",new { id = item.MaNV})" class="btn btn-outline-dark">Sửa</a>
                    <a href="@Url.Action("Details","NHANVIENs",new { id = item.MaNV })" class="btn btn-outline-info">Chi tiết</a>
                    <a href="@Url.Action("Delete","NHANVIENs",new { id = item.MaNV })" class="btn btn-outline-danger">Xóa</a>
                </td>
            </tr>
        }

    </table>
</div>
<div class="card-footer">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount;
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }

            .MenuTrang li a {
                color: black;
                float: left;
                padding: 8px 16px;
                text-decoration: none;
            }
    </style>
</div>