QuanLyKho/Models/KHOHANG.cs
namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("KHOHANG")]
    public partial class KHOHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOHANG()
        {
            VITRIKHOes = new HashSet<VITRIKHO>();
        }

        [Key]
        [Display(Name ="Mã kho hàng")]
        public int MaKhoHang { get; set; }

        [Display(Name ="Loại kho")]
        public String LoaiKho { get; set; }


        [Required(ErrorMessage = "Tên kho hàng không được để trống")]
        [Display(Name = "Tên kho hàng")]
        [StringLength(255)]
        public string TenKhohang { get; set; }

        [Required(ErrorMessage = "Địa chỉ kho hàng không được để trống.")]
        [Display(Name = "Địa chỉ")]
        [StringLength(255)]
        public string DiaChi { get; set; }

        [Required(ErrorMessage = "Số điện thoại đơn hàng không được để trống")]
        [RegularExpression(@"^0\d{9,10}$", ErrorMessage = "Số điện thoại không hợp lệ")]
        [Display(Name = "Số điện thoại kho hàng")]
        [StringLength(20)]
        public string SDTKho { get; set; }

        [Required(ErrorMessage ="Sức chứa không được để trống")]
        [Display(Name ="Sức chứa")]
        public int Succhua { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VITRIKHO> VITRIKHOes { get; set; }
    }
}

QuanLyKho/Controllers/KHOHANGsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyKho.Models;

namespace QuanLyKho.Controllers
{
    public class KHOHANGsController : Controller
    {
        private QLKhoDBContext db = new QLKhoDBContext();

        // GET: KHOHANGs
        public ActionResult Index(String thanhPho, String loaiKho)
        {
            if (Session["Taikhoan"] != null)
            {
                var khohang = db.KHOHANGs.AsQueryable();

                if (!string.IsNullOrEmpty(thanhPho))
                {
                    var diaChiFilter = thanhPho.Trim().ToLower();
                    var diaChiFilterEnd = diaChiFilter.Split(',').LastOrDefault()?.Trim();
                    if (!string.IsNullOrEmpty(diaChiFilterEnd))
                    {
                        khohang = khohang.Where(ncc => ncc.DiaChi.ToLower().EndsWith(diaChiFilterEnd));
                    }
                }
                if (!string.IsNullOrEmpty(loaiKho))
                {
                    khohang = khohang.Where(sp => sp.LoaiKho == loaiKho);
                }

                return View(khohang.ToList());
            }
            else
                return RedirectToAction("Dangnhap", "Login");
        }

        // GET: KHOHANGs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHOHANG kHOHANG = db.KHOHANGs.Find(id);
            if (kHOHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHOHANG);
        }

        // GET: KHOHANGs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KHOHANGs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKhoHang,TenKhohang,DiaChi,SDTKho")] KHOHANG kHOHANG)
        {
            if (ModelState.IsValid)
            {
                db.KHOHANGs.Add(kHOHANG);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kHOHANG);
        }

        // GET: KHOHANGs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHOHANG kHOHANG = db.KHOHANGs.Find(id);
            if (kHOHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHOHANG);
        }

        // POST: KHOHANGs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKhoHang,TenKhohang,DiaChi,SDTKho")] KHOHANG kHOHANG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kHOHANG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kHOHANG);
        }

        // GET: KHOHANGs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHOHANG kHOHANG = db.KHOHANGs.Find(id);
            if (kHOHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHOHANG);
        }

        // POST: KHOHANGs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KHOHANG kHOHANG = db.KHOHANGs.Find(id);
            db.KHOHANGs.Remove(kHOHANG);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteSelected(string[] selectedIds)
        {
            if (selectedIds != null && selectedIds.Length > 0)
            {
                foreach (var id in selectedIds)
                {
                    if (int.TryParse(id, out int Id))
                    {
                        var xoa = db.KHOHANGs.Find(Id);
                        if (xoa != null)
                        {
                            db.KHOHANGs.Remove(xoa);
                        }
                    }
                }
                db.SaveChanges();
            }

            return new EmptyResult();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyKho/Views/KHOHANGs/Create.cshtml
@model QuanLyKho.Models.KHOHANG

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KHOHANG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenKhohang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKhohang, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập tên kho hàng" } })
                @Html.ValidationMessageFor(model => model.TenKhohang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập địa chỉ" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDTKho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDTKho, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập số điện thoại kho" } })
                @Html.ValidationMessageFor(model => model.SDTKho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-outline-success" style="margin-right:5px" />
                <a href="@Url.Action("Index","KHOHANGs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
            </div>
        </div>
    </div>
}

QuanLyKho/Views/KHOHANGs/Delete.cshtml
@model QuanLyKho.Models.KHOHANG

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KHOHANG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenKhohang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenKhohang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDTKho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDTKho)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-outline-danger" style="margin-right:8px" />
            <a href="@Url.Action("Index","KHOHANGs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
        </div>
    }
</div>

QuanLyKho/Views/KHOHANGs/Details.cshtml
@model QuanLyKho.Models.KHOHANG

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Details</h2>

<div>
    <h4>KHOHANG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenKhohang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenKhohang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDTKho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDTKho)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit","KHOHANGs",new { id = Model.MaKhoHang})" class="btn btn-outline-success">Sửa</a>
    <a href="@Url.Action("Index","KHOHANGs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
</p>

QuanLyKho/Views/KHOHANGs/Edit.cshtml
@model QuanLyKho.Models.KHOHANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KHOHANG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKhoHang)

        <div class="form-group">
            @Html.LabelFor(model => model.TenKhohang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKhohang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKhohang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDTKho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDTKho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDTKho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sửa" class="btn btn-outline-success" style="margin-right:5px" />
                <a href="@Url.Action("Index","KHOHANGs")" class="btn btn-outline-success">Trở về <i class="fas fa-arrow-circle-left"></i></a>
            </div>
        </div>
    </div>
}

QuanLyKho/Views/KHOHANGs/Index.cshtml
@model IEnumerable<QuanLyKho.Models.KHOHANG>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Index kho hang</h2>

<a href="@Url.Action("Create","KHOHANGs")" class="btn btn-outline-success" style="padding:6px 14px"><i class="fas fa-plus"></i></a>
<button id="deleteSelectedKH" class="btn btn-outline-danger"><i class="fas fa-trash-alt"></i></button>
<div class=" card-body">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th><input type="checkbox" id="checkAll" /></th>
                <th>Kho</th>
                <th>
                    <form method="get">
                        <div class="form-group">
                            <label>Địa chỉ:</label>
                            <select name="thanhPho" class="form-control" onchange="this.form.submit()" style="width:129px">
                                <option value="">--Thành phố--</option>
                                <option value="TP.HCM">TP.HCM</option>
                                <option value="TP.Hà Nội">TP.Hà Nội</option>
                            </select>
                        </div>
                    </form>
                </th>
                <th>Số điện thoại</th>

                <th>
                    <form method="get">
                        <div class="form-group">
                            <label>Loại kho:</label>
                            <select name="loaiKho" class="form-control" onchange="this.form.submit()" style="width:129px">
                                <option value="">--loại kho--</option>
                                <option value="Kho đông lạnh">Kho đông lạnh</option>
                                <option value="Kho thường">Kho thường</option>
                            </select>
                        </div>

                    </form>
                <th>Sức chứa</th>
                </th>
                <th>Chưc năng</th>
            </tr>
        </thead>

        <tbody class="search">
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center"><input type="checkbox" class="checkbox" value="@item.MaKhoHang" /></td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenKhohang)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DiaChi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SDTKho)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LoaiKho)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Succhua)
                    </td>
                    <td style="display:flex; border-bottom:0px">
                        <a href="@Url.Action("Edit","KHOHANGs",new { id = item.MaKhoHang})" class="btn btn-outline-dark">Sửa</a>
                        <a href="@Url.Action("Details","KHOHANGs",new { id = item.MaKhoHang })" class="btn btn-outline-info">Chi tiết</a>
                        <a href="@Url.Action("Delete","KHOHANGs",new { id = item.MaKhoHang })" class="btn btn-outline-danger">Xóa</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>